---
- alias: timer_toaster_on
  trigger:
    - platform: state
      entity_id: input_boolean.toaster
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.toaster
    - service: timer.start
      entity_id: timer.toaster

- alias: timer_toaster_off
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: 'timer.toaster'
    - platform: state
      entity_id: input_boolean.toaster
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.toaster
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.toaster
    - service: timer.cancel
      entity_id: timer.toaster

- alias: nexa_remote_g_on
  trigger:
    - platform: state
      entity_id: switch.nexa_remote_g
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: group.lights

- alias: nexa_remote_g_off
  trigger:
    - platform: state
      entity_id: switch.nexa_remote_g
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights

# - alias: motion_hallway_on
#   trigger:
#     - platform: state
#       entity_id: switch.motion_hallway
#       from: 'off'
#       to: 'on'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.hallway
#         brightness: 255

# - alias: motion_hallway_off
#   trigger:
#     - platform: state
#       entity_id: switch.motion_hallway
#       from: 'on'
#       to: 'off'
#   action:
#     - service: light.turn_off
#       data:
#         entity_id: light.hallway
#         brightness: 0
