---

# https://www.home-assistant.io/components/automation/

- alias: notifications_about_device_trackers_entering
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.carl
      from: not_home
      to: home
    - platform: state
      entity_id: person.johanna
      from: not_home
      to: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
    - service_template: notify.gassistant
      data_template:
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'

- alias: notifications_about_device_trackers_leaving
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.carl
      from: home
    - platform: state
      entity_id: person.johanna
      from: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
    - service_template: notify.gassistant
      entity_id: media_player.home
      data_template:
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'

- alias: When one user is at activate the default scene
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.tracker_home
      from: not_home
      to: home
  action:
    - service: script.turn_on
      entity_id: script.daytime

- alias: When all users are away turn off all things
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.tracker_home
      to: not_home
      from: home
  action:
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id: switch.screen
    - service: xiaomi_miio.fan_set_favorite_level
      data:
        entity_id: fan.xiaomi_miio_device
        level: 14
    - service: xiaomi_miio.fan_set_speed
      data:
        entity_id: fan.xiaomi_miio_device
        speed: Favorite

- alias: Activate the sleep_in_an_hour script at 22:00:00
  initial_state: true
  trigger:
    platform: time
    at: '22:00'
  action:
    - service: script.turn_on
      entity_id: script.sleep_in_an_hour

- alias: Xiaomi Air Purifier - Change Air Purifier level based on input number
  trigger:
    platform: state
    entity_id: input_number.xiaomi_fan_favorite_level
  action:
    - service: xiaomi_miio.fan_set_favorite_level
      data_template:
        entity_id: fan.xiaomi_miio_device
        level: "{{ trigger.to_state.state | int }}"

- alias: Xiaomi Air Purifier - Change input number based on Air Purifier level
  trigger:
    platform: state
    entity_id: sensor.air_purifier_favorite_level
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.xiaomi_fan_favorite_level
        value: "{{ trigger.to_state.state | int }}"

- alias: Turn off LG TV when Shield is turned off
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.lg_tv_off

- alias: Wakeup in half an hour at 06:30 every day
  trigger:
    platform: time
    at: "06:30:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.wakeup_in_half_an_hour

- alias: Notify Johanna when the battery of phone is below certain level
  trigger:
    - below: 30
      device_id: 8f07c81adbef4b12beaad8dbd09625b4
      domain: sensor
      entity_id: sensor.sm_g955f_battery_level
      platform: device
      type: battery_level
  condition:
    condition: state
    entity_id: sensor.sm_g955f_battery_state
    state: discharging
  action:
    - service: notify.mobile_app_sm_g955f
      data:
        message: Battery
        title: Battery level below 30%
    - service: notify.gassistant
      data:
        message: Johanna it is time to charge your phone.

- alias: Notify Carl about low battery level
  trigger:
  - below: 30
    device_id: a6c2febc07ce437cbe8ee51fcfd860c9
    domain: sensor
    entity_id: sensor.sm_g975f_battery_level
    platform: device
    type: battery_level
  condition:
    condition: state
    entity_id: sensor.sm_g975f_battery_state
    state: discharging
  action:
    - service: notify.gassistant
      data:
        message: Carl it is time to charge your phone.

