---

# https://www.home-assistant.io/components/automation/

- alias: notifications_about_device_trackers_entering
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_118136931442668540655
      from: not_home
      to: work
    - platform: state
      entity_id: device_tracker.iphone
      from: not_home
      to: work
    - platform: state
      entity_id: person.carl
      from: not_home
      to: home
    - platform: state
      entity_id: person.carl
      from: not_home
      to: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
    - service_template: 'tts.google_say'
      entity_id: media_player.home
      data_template:
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'

- alias: notifications_about_device_trackers_leaving
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_118136931442668540655
      from: work
    - platform: state
      entity_id: device_tracker.iphone
      from: work
    - platform: state
      entity_id: person.carl
      from: home
    - platform: state
      entity_id: group.johanna
      from: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
    - service_template: 'tts.google_say'
      entity_id: media_player.home
      data_template:
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'

- alias: When one user is at home start the Harmony Hub activity Home and turn on the default scene
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.tracker_home
      from: not_home
      to: home
    - platform: state
      entity_id: input_boolean.test
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.harmony_hub_clean
    - service: script.turn_on
      entity_id: script.daytime

- alias: When all users are away start the Harmony Hub activity Away
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.tracker_home
      to: not_home
      from: home
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: Away
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.screen
    - service: fan.xiaomi_miio_set_favorite_level
      data:
        entity_id: fan.xiaomi_miio_device
        level: 14
    - service: fan.set_speed
      data:
        entity_id: fan.xiaomi_miio_device
        speed: Favorite

- alias: Activate the sleep_in_an_hour script at 22:00:00
  initial_state: true
  trigger:
    platform: time
    at: '22:00'
  action:
    - service: script.turn_on
      entity_id: script.sleep_in_an_hour


- alias: Xiaomi Air Purifier - Change Air Purifier level based on input number
  trigger:
    platform: state
    entity_id: input_number.xiaomi_fan_favorite_level
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      data_template:
        entity_id: fan.xiaomi_miio_device
        level: "{{ trigger.to_state.state | int }}"

- alias: Xiaomi Air Purifier - Change input number based on Air Purifier level
  trigger:
    platform: state
    entity_id: sensor.air_purifier_favorite_level
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.xiaomi_fan_favorite_level
        value: "{{ trigger.to_state.state | int }}"
