---
- alias: timer_toaster_on
  trigger:
    - platform: state
      entity_id: input_boolean.toaster
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.toaster
    - service: timer.start
      entity_id: timer.toaster

- alias: timer_toaster_off
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: 'timer.toaster'
    - platform: state
      entity_id: input_boolean.toaster
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.toaster
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.toaster
    - service: timer.cancel
      entity_id: timer.toaster

- alias: nexa_remote_g_on
  trigger:
    - platform: state
      entity_id: switch.nexa_remote_g
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: group.lights

- alias: nexa_remote_g_off
  trigger:
    - platform: state
      entity_id: switch.nexa_remote_g
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights

# - alias: motion_hallway_on
#   trigger:
#     - platform: state
#       entity_id: switch.motion_hallway
#       from: 'off'
#       to: 'on'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.hallway
#         brightness: 255

# - alias: motion_hallway_off
#   trigger:
#     - platform: state
#       entity_id: switch.motion_hallway
#       from: 'on'
#       to: 'off'
#   action:
#     - service: light.turn_off
#       data:
#         entity_id: light.hallway
#         brightness: 0

# https://www.home-assistant.io/docs/automation/trigger/
# https://www.home-assistant.io/components/notify.twilio_sms/
# - service: notify.twilio_sms
#   data:
#     message: 'Carl has arrived at work'
#     target:
#       - '+46702720540'

- alias: notifications_about_device_trackers_entering
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_118136931442668540655
      to: work
    - platform: state
      entity_id: device_tracker.iphone
      to: work
    - platform: state
      entity_id: device_tracker.iphone
      to: 'WeMind'
    - platform: state
      entity_id: group.tracker_carl
      to: home
    - platform: state
      entity_id: group.tracker_johanna
      to: home
    - platform: state
      entity_id: input_boolean.test
      to: 'on'
  action:
    - service_template: 'notify.pushover'
      data_template:
        title: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
    - service_template: 'tts.google_say'
      entity_id: media_player.srsx77
      data_template:
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'

- alias: notifications_about_device_trackers_leaving
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_118136931442668540655
      from: work
    - platform: state
      entity_id: device_tracker.iphone
      from: work
    - platform: state
      entity_id: device_tracker.iphone
      from: 'WeMind'
    - platform: state
      entity_id: group.tracker_carl
      from: home
    - platform: state
      entity_id: group.tracker_johanna
      from: home
  action:
    - service_template: 'notify.pushover'
      data_template:
        title: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
    - service_template: 'tts.google_say'
      entity_id: media_player.srsx77
      data_template:
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'

- alias: "start harmony activity with input boolean"
    initial_state: off
    trigger:
      - platform: state
        entity_id: input_boolean.test
        to: 'on'
    action:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "SHIELD TV"