---

- alias: nexa_remote_g_on
  trigger:
    - platform: state
      entity_id: switch.nexa_remote_g
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: group.lights

- alias: nexa_remote_g_off
  trigger:
    - platform: state
      entity_id: switch.nexa_remote_g
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights

- alias: notifications_about_device_trackers_entering
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_118136931442668540655
      from: not_home
      to: work
    - platform: state
      entity_id: device_tracker.iphone
      from: not_home
      to: work
    - platform: state
      entity_id: group.tracker_carl
      from: not_home
      to: home
    - platform: state
      entity_id: group.tracker_johanna
      from: not_home
      to: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
    - service_template: 'tts.google_say'
      entity_id: media_player.srsx77
      data_template:
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'

- alias: notifications_about_device_trackers_leaving
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_118136931442668540655
      from: work
    - platform: state
      entity_id: device_tracker.iphone
      from: work
    - platform: state
      entity_id: group.tracker_carl
      from: home
    - platform: state
      entity_id: group.tracker_johanna
      from: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
    - service_template: 'tts.google_say'
      entity_id: media_player.srsx77
      data_template:
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'

- alias: When one user is at home start the Harmony Hub activity Home and turn on the default scene
  trigger:
    - platform: state
      entity_id: group.tracker_home
      from: not_home
      to: home
  action:
    - service: switch.turn_off
      entity_id: switch.harmony_hub_clean
    - service: script.turn_on
      entity_id: script.daytime
    - service: script.turn_on
      entity_id: script.daytime
    - service: switch.turn_on
      entity_id: switch.z9124
    - service: script.turn_on
      entity_id: script.z9124_medium

- alias: When all users are away start the Harmony Hub activity Away
  trigger:
    - platform: state
      entity_id: group.tracker_home
      to: not_home
      from: home
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: Away
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.screen
    - service: script.turn_on
      entity_id: script.z9124_turbo

- alias: When state of input_boolean.z9124 changes toggle activate script z9124_toggle
  trigger:
    - platform: state
      entity_id: input_boolean.z9124
  action:
    - service: script.turn_on
      entity_id: script.z9124_toggle

- alias: Activate the sleep_in_an_hour script at 22:00:00
  trigger:
    platform: time
    at: '22:00'
  action:
    - service: script.turn_on
      entity_id: script.sleep_in_an_hour
