---
- alias: timer_toaster_on
  trigger:
    - platform: state
      entity_id: input_boolean.toaster
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.toaster
    - service: timer.start
      entity_id: timer.toaster

- alias: timer_toaster_off
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: 'timer.toaster'
    - platform: state
      entity_id: input_boolean.toaster
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.toaster
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.toaster
    - service: timer.cancel
      entity_id: timer.toaster
