---
# https://www.home-assistant.io/components/automation/

- alias: notifications_about_device_trackers_entering
  id: 6a2437ba-6f0d-47da-ba76-99fa343eefce
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.carl
      from: not_home
      to: home
    - platform: state
      entity_id: person.johanna
      from: not_home
      to: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'
    - service_template: notify.gassistant
      data_template:
        message: '{{ trigger.to_state.name.split(" ")[0] }} has arrived at {{ trigger.to_state.state }}'

- alias: notifications_about_device_trackers_leaving
  id: 27d9e431-a560-4a57-99a0-bc862981c1a4
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.carl
      from: home
    - platform: state
      entity_id: person.johanna
      from: home
  action:
    - service_template: notify.pushover
      data_template:
        title: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'
    - service_template: notify.gassistant
      entity_id: media_player.home
      data_template:
        message: '{{ trigger.from_state.name.split(" ")[0] }} has left {{ trigger.from_state.state }}'

- alias: When one user is at activate the default scene
  id: 11cf51f6-e1c4-41da-b0fb-7a3b04387829
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.tracker_home
      from: not_home
      to: home
  action:
    - service: script.turn_on
      entity_id: script.daytime

- alias: When all users are away turn off all things
  id: f59282b1-c8ba-41c4-9337-f907bfaf858f
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.tracker_home
      to: not_home
      from: home
  action:
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id: switch.screen
    - service: switch.turn_off
      entity_id: switch.bathroom
    - service: fan.set_preset_mode
      data:
        entity_id: fan.zhimi_airpurifier_mc1
        preset_mode: Favorite
    - service: number.set_value
      target:
        entity_id: number.zhimi_airpurifier_mc1_favorite_level
      data:
        value: '17'

- alias: Activate the sleep_in_an_hour script at 22:00:00
  id: edb33fad-78de-4ebf-9f10-93e10e735bb6
  initial_state: true
  trigger:
    platform: time
    at: '22:00'
  action:
    - service: script.turn_on
      entity_id: script.sleep_in_an_hour

- alias: Turn off LG TV when Shield is turned off
  id: a891c365-bb65-42b7-aa86-fad91f0cf16d
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.lg_tv_off
    - service: script.turn_on
      entity_id: script.rotel_amp_power_off

- alias: Set Rotel Amp to media mode when Shield is turned on
  id: e7cce58b-0780-4046-bc10-7f70eff656fa
  trigger:
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'standby'
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'playing'
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'idle'
  action:
    - service: script.turn_on
      entity_id: script.rotel_media_mode

- alias: Wakeup in half an hour at 06:30 every day
  id: 8c00c075-f201-4083-b8eb-e01998828220
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.wakeup_in_half_an_hour

- alias: Notify Johanna when the battery of phone is below certain level
  id: b693415a-a8e0-4bd2-b17e-f4684e912c84
  trigger:
    - below: 30
      device_id: 8f07c81adbef4b12beaad8dbd09625b4
      domain: sensor
      entity_id: sensor.sm_g955f_battery_level
      platform: device
      type: battery_level
  condition:
    - condition: state
      entity_id: sensor.sm_g955f_battery_state
      state: discharging
    - condition: state
      entity_id: binary_sensor.daytime
      state: 'on'
  action:
    - service: notify.gassistant
      data:
        message: Johanna it is time to charge your phone.

- alias: Notify Carl about low battery level
  id: 06a9112c-f761-421f-a015-e313bfd18407
  trigger:
    - below: 30
      device_id: a6c2febc07ce437cbe8ee51fcfd860c9
      domain: sensor
      entity_id: sensor.sm_g781b_battery_level
      platform: device
      type: battery_level
  condition:
    - condition: state
      entity_id: sensor.sm_g781b_battery_level
      state: discharging
    - condition: state
      entity_id: binary_sensor.daytime
      state: 'on'
  action:
    - service: notify.gassistant
      data:
        message: Carl it is time to charge your phone.
