---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.3097048
  longitude: 18.0752532
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    automation:
      hidden: true
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        192.168.1.0/24:
          - ddbc7a2301d74d609308958f9f07d0b7
      allow_bypass_login: true
    - type: homeassistant

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Configure Lovelace UI using yaml in ui-lovelace.yaml
# https://www.home-assistant.io/lovelace/yaml-mode
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-more-info-card/more-info-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/button-entity-row/button-entity-row.js
      type: module

# Enables configuration UI
config:

http:
  server_port: 8123
  #  ssl_certificate: /ssl/fullchain.pem
  #  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.1
    - 127.0.0.1

# This integration is a meta-component and configures a default set of integrations for
#  Home Assistant to load. https://www.home-assistant.io/integrations/default_config
hassio:
mobile_app:
zeroconf:

recorder:
  db_url: 'mysql://homeassistant:homeassistant@192.168.1.2/homeassistant?charset=utf8'

history:
  include:
    domains:
      - switch
      - person

logbook:

influxdb:
  host: 192.168.1.2
  database: homeassistant

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

light:
  - platform: group
    name: Kitchen Table
    entities:
      - light.kitchen_table_left
      - light.kitchen_table_right

  - platform: group
    name: Kitchen Fan
    entities:
      - light.kitchen_fan_left
      - light.kitchen_fan_right

  - platform: group
    name: Living Room Ceiling
    entities:
      - light.living_room_ceiling_1
      - light.living_room_ceiling_2
      - light.living_room_ceiling_3

  - platform: group
    name: Living Area Lights
    entities:
      - light.bed
      - light.behind_tv
      - light.desktop
      - light.kitchen_fan
      - light.frank

binary_sensor:
  - platform: template
    sensors:
      daytime:
        value_template: "{{ '08:00' < states('sensor.time') < '22:40' }}"
        friendly_name: Is Daytime

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: load_1m
      - type: load_15m
      - type: last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0

  - platform: tellstick
    only_named:
      - id: 135
        name: Outside

  - platform: time_date
    display_options:
      - 'time'

  # https://www.home-assistant.io/components/template
  - platform: template
    sensors:
      harmony_hub:
        friendly_name: 'Harmony Hub'
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      air_purifier_humidity:
        value_template: '{{ states.fan.xiaomi_miio_device.attributes.humidity }}'
        friendly_name: Air Purifier Humidity
        unit_of_measurement: '%'
        device_class: humidity
      air_purifier_temperature:
        value_template: '{{ states.fan.xiaomi_miio_device.attributes.temperature }}'
        friendly_name: Air Purifier Temperature
        unit_of_measurement: '°C'
        device_class: temperature
      air_purifier_favorite_level:
        value_template: '{{ states.fan.xiaomi_miio_device.attributes.favorite_level }}'
        friendly_name: Air Purifier Favorite Level
      air_purifier_air_quality:
        value_template: '{{ states.fan.xiaomi_miio_device.attributes.aqi }}'
        friendly_name: Air Purifier Air Quality
        unit_of_measurement: 'AQI'
      sleep_time_in_bed_friendly:
        value_template: >-
          {% set sleep = states('sensor.sleep_minutes_asleep') | int %}
          {{ "{:01d}h {:02d}m".format((sleep % 3600) // 60, (sleep % 3600) % 60) }}
        friendly_name: Sleep Time in Bed Friendly

  - platform: fitbit
    clock_format: 24H
    monitored_resources:
      - 'body/weight'
      - 'devices/battery'
      - 'sleep/timeInBed'
      - 'sleep/minutesAsleep'
      - 'activities/tracker/steps'

  - platform: command_line
    name: CPU Temperature
    command: 'cat /sys/class/thermal/thermal_zone0/temp'
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: rest
    resource: http://wtfismyip.com/json
    name: External IP
    value_template: '{{ value_json.YourFuckingIPAddress }}'

climate:
  - platform: generic_thermostat
    name: temperature_outside
    heater: input_boolean.fake_heater
    target_sensor: sensor.outside_temperature
    initial_hvac_mode: 'off'
    target_temp: 21

# Text to speech
tts:
  - platform: google_translate

# Cloud
# https://www.home-assistant.io/cloud/google_assistant/
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - scene
        - script
        - climate
        - sensor
      exclude_entities:
        - switch.nexa_remote_g
        - light.kitchen_table_left
        - light.kitchen_table_right
        - light.kitchen_fan_left
        - light.kitchen_fan_right
        - light.living_room_ceiling_1
        - light.living_room_ceiling_2
        - light.living_room_ceiling_3
        - switch.desktop
        - switch.bathroom_ceiling
        - script.lg_tv_on
        - script.lg_tv_off

    entity_config:
      light.desktop:
        room: Office
      light.bathroom_ceiling:
        room: Bathroom
      light.hallway_ceiling:
        room: Hallway
      light.kitchen_table:
        room: Kitchen
      switch.coffeemaker:
        room: Kitchen
      switch.toaster:
        room: Kitchen
      script.clean_kitchen:
        room: Kitchen
      climate.temperature_outside_skanstull:
        room: Outside

# Tellstick
tellstick:
  host: core-tellstick
  port: [50800, 50801]
  signal_repetitions: 3

zwave:
  usb_path: /dev/ttyACM0

zone:
  - name: home
    latitude: 59.3097048
    longitude: 18.0752532
    radius: 100
    icon: mdi:account-multiple
  - name: work
    latitude: 59.311335
    longitude: 18.030075
    radius: 100
    icon: mdi:briefcase
  - name: 'Ann-Marie'
    latitude: 59.265861
    longitude: 18.089933
    radius: 100
    icon: mdi:account

# https://www.home-assistant.io/components/asuswrt/
asuswrt:
  host: 192.168.1.1
  username: cbackstrom
  password: !secret router_password

device_tracker:
  - platform: asuswrt

media_player:
  - platform: kodi
    host: 192.168.1.7
    # https://github.com/home-assistant/home-assistant/issues/6546
    enable_websocket: false
    turn_off_action:
      - service: media_player.media_stop
        data:
          entity_id: media_player.kodi
  - platform: androidtv
    name: Shield
    host: 192.168.1.7
    adb_server_ip: 127.0.0.1
    apps:
      com.netflix.ninja: 'Netflix'
    state_detection_rules:
      'com.plexapp.android':
        - 'playing':
            'media_session_state': 3
        - 'paused':
            'media_session_state': 2
        - 'standby'
      'se.svt.android.svtplay':
        - 'playing':
            'wake_lock_size': 4
        - 'paused':
            'wake_lock_size': 3
        - 'standby'

# https://home-assistant.io/components/media_player.spotify/
spotify:
  client_id: 7bfa4dc5b8fa4af69ca572b2cb615540
  client_secret: !secret spotify_client_secret

webostv:
  name: LG TV
  host: 192.168.1.10

logger:
  default: info
  logs:
    homeassistant.components.media_player.spotify: info
    homeassistant.components.media_player.androidtv.adb_shell: debug

timer:
  clean:
    name: Clean Timer
    duration: '00:30:00'
  toaster:
    name: Toaster Timer
    duration: '00:03:00'
  coffeemaker:
    name: Coffeemaker Timer
    duration: '00:60:00'
remote:
  - platform: harmony
    host: 192.168.1.42
    name: Harmony Hub
    activity: Home

system_health:

person:
  - name: Carl
    id: ddbc7a2301d74d609308958f9f07d0b7
    user_id: ddbc7a2301d74d609308958f9f07d0b7
    device_trackers:
      - device_tracker.sm_g781b
  - name: Johanna
    id: ff088ba35b4a4730a5eb3832edb46922
    user_id: ff088ba35b4a4730a5eb3832edb46922
    device_trackers:
      - device_tracker.sm_g955f
      - device_tracker.galaxy_s8

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.11
    token: 586854367345797931635945364a6a72

fan:
  - platform: xiaomi_miio
    host: 192.168.1.27
    token: b8d8625068ac729c36e677462fecca53
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.1.22
    token: 78515254e630a84d6e38e82141bd6da4

rest_command:
  cast_site:
    url: 'http://localhost:9898/cast_site'
    payload: '{"device": "{{ device }}", "url": "{{ url }}"}'
    method: post
    content_type: 'application/json'
    verify_ssl: false

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include automations_manual.yaml
script: !include scripts.yaml
switch: !include switches.yaml
notify: !include notifiers.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
input_text: !include input_texts.yaml
