---

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.3097048
  longitude: 18.0752532
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    automation:
      hidden: true
  auth_providers:
     - type: legacy_api_password
       api_password: !secret http_password
     - type: homeassistant

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Configure Lovelace UI using yaml in ui-lovelace.yaml
# https://www.home-assistant.io/lovelace/yaml-mode
lovelace:
  mode: yaml
  resources:
    - url: /local/mini-media-player-bundle.js?v=1.8.0
      type: module
    - url: /local/slider-entity-row.js
      type: module
    # https://github.com/benct/lovelace-xiaomi-vacuum-card
    - url: /local/xiaomi-vacuum-card.js?v=3.0.1
      type: module
    # https://maykar.github.io/custom-header/#installation/manual
    - url: /local/custom-header.js?v=1.3.8
      type: module


# Enables configuration UI
config:

http:
  base_url: https://hassio.dahler.se
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.1
    - 127.0.0.1

# This integration is a meta-component and configures a default set of integrations for
#  Home Assistant to load. https://www.home-assistant.io/integrations/default_config
hassio:
mobile_app:
zeroconf:

recorder:
  db_url: 'mysql://homeassistant:homeassistant@192.168.1.2/homeassistant?charset=utf8'

history:
  include:
    domains:
      - switch
      - person

logbook:

influxdb:
  host: 192.168.1.2
  database: homeassistant

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

light:
  - platform: group
    name: Kitchen Table
    entities:
      - light.kitchen_table_left
      - light.kitchen_table_right

  - platform: group
    name: Kitchen Fan
    entities:
      - light.kitchen_fan_left
      - light.kitchen_fan_right

  - platform: group
    name: Living Room Ceiling
    entities:
      - light.living_room_ceiling_1
      - light.living_room_ceiling_2
      - light.living_room_ceiling_3

  - platform: group
    name: Living Area Lights
    entities:
      - light.bed
      - light.behind_tv
      - light.desktop
      - light.kitchen_fan
      - light.frank

  - platform: template
    lights:
      bathroom_ceiling:
        friendly_name: Bathroom Ceiling
        entity_id:
          - switch.bathroom_ceiling
        value_template: '{{ is_state("switch.bathroom_ceiling", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.bathroom_ceiling
        turn_off:
          service: switch.turn_off
          entity_id: switch.bathroom_ceiling

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: load_1m
      - type: load_15m
      - type: last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0

  - platform: tellstick

  # https://www.home-assistant.io/components/template
  - platform: template
    sensors:
      harmony_hub:
        friendly_name: "Harmony Hub"
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      air_purifier_humidity:
        value_template: "{{ states.fan.xiaomi_miio_device.attributes.humidity }}"
        friendly_name: Air Purifier Humidity
        unit_of_measurement: "%"
        device_class: humidity
      air_purifier_temperature:
        value_template: "{{ states.fan.xiaomi_miio_device.attributes.temperature }}"
        friendly_name: Air Purifier Temperature
        unit_of_measurement: "°C"
        device_class: temperature
      air_purifier_favorite_level:
        value_template: "{{ states.fan.xiaomi_miio_device.attributes.favorite_level }}"
        friendly_name: Air Purifier Favorite Level
      air_purifier_air_quality:
        value_template: "{{ states.fan.xiaomi_miio_device.attributes.aqi }}"
        friendly_name: Air Purifier Air Quality
        unit_of_measurement: "AQI"

  - platform: fitbit
    clock_format: 24H
    monitored_resources:
      - "body/weight"
      - "devices/battery"
      - "sleep/timeInBed"
      - "activities/tracker/steps"

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: rest
    resource: http://wtfismyip.com/json
    name: External IP
    value_template: '{{ value_json.YourFuckingIPAddress }}'

climate:
  - platform: generic_thermostat
    name: temperature_outside_skanstull
    heater: input_boolean.fake_heater
    target_sensor:  sensor.235_temperature
    initial_hvac_mode: "off"
    target_temp: 21

# Text to speech
tts:
  - platform: google_translate

# Cloud
# https://www.home-assistant.io/cloud/google_assistant/
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - scene
        - script
        - climate
        - sensor
      exclude_entities:
        - switch.nexa_remote_g
        - light.kitchen_table_left
        - light.kitchen_table_right
        - light.kitchen_fan_left
        - light.kitchen_fan_right
        - switch.desktop
        - switch.bathroom_ceiling
        - script.lg_tv_on
        - script.lg_tv_off

    entity_config:
      light.desktop:
        room: Office
      light.bathroom_ceiling:
        room: Bathroom
      light.hallway_ceiling:
        room: Hallway
      light.kitchen_table:
        room: Kitchen
      switch.coffeemaker:
        room: Kitchen
      switch.toaster:
        room: Kitchen
      script.clean_kitchen:
        room: Kitchen
      climate.temperature_outside_skanstull:
        room: Outside

# Tellstick
tellstick:
  host: core-tellstick
  port: [50800, 50801]
  signal_repetitions: 3

zone:
  - name: home
    latitude: 59.3097048
    longitude: 18.0752532
    radius: 100
    icon: mdi:account-multiple
  - name: work
    latitude: 59.311335
    longitude: 18.030075
    radius: 100
    icon: mdi:briefcase
  - name: 'Ann-Marie'
    latitude: 59.265861
    longitude: 18.089933
    radius: 100
    icon: mdi:account

# https://www.home-assistant.io/components/asuswrt/
asuswrt:
  host: 192.168.1.1
  username: cbackstrom
  password: !secret router_password

device_tracker:
  - platform: asuswrt

media_player:
  - platform: kodi
    host: 192.168.1.7
    # https://github.com/home-assistant/home-assistant/issues/6546
    enable_websocket: false
    turn_off_action:
      - service: media_player.media_stop
        data:
          entity_id: media_player.kodi
  - platform: androidtv
    name: Shield
    host: 192.168.1.7
    adb_server_ip: 127.0.0.1
    apps:
      com.netflix.ninja: "Netflix"
    state_detection_rules:
      'com.plexapp.android':
        - 'playing':
            'media_session_state': 3
        - 'paused':
            'media_session_state': 2
        - 'standby'
      'se.svt.android.svtplay':
        - 'playing':
            'wake_lock_size': 4
        - 'paused':
            'wake_lock_size': 3
        - 'standby'


# https://home-assistant.io/components/media_player.spotify/
spotify:
  client_id: 7bfa4dc5b8fa4af69ca572b2cb615540
  client_secret: !secret spotify_client_secret

webostv:
  name: LG TV
  host: 192.168.1.10

logger:
  default: info
  logs:
    homeassistant.components.media_player.spotify: info
    homeassistant.components.media_player.androidtv.adb_shell: debug

input_boolean:
  test:
    initial: false
  movie:
    initial: false
  camac:
    initial: true
  fake_heater:
    initial: false
  anslut_fan_oscillating:
    initial: false
  anslut_fan:
    initial: false

input_number:
  xiaomi_fan_favorite_level:
    name: Xiaomi Fan Favourite Level
    min: 0
    max: 14
    step: 1
input_select:
  anslut_fan_speed:
    options:
      - low
      - medium
      - high

timer:
  clean:
    name: Clean Timer
    duration: '00:30:00'
  toaster:
    name: Toaster Timer
    duration: '00:03:00'
  coffeemaker:
    name: Coffeemaker Timer
    duration: '00:60:00'

notify:
  - name: 'pushover'
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: 'gassistant'
    platform: rest
    method: POST_JSON
    resource: http://localhost:5001/broadcast_message

remote:
  - platform: harmony
    host: 192.168.1.42
    name: Harmony Hub
    activity: Home

system_health:

person:
  - name: Carl
    id: ddbc7a2301d74d609308958f9f07d0b7
    user_id: ddbc7a2301d74d609308958f9f07d0b7
    device_trackers:
      - device_tracker.sm_g975f
      - device_tracker.galaxy_s10
  - name: Johanna
    id: 82e52e7a9e574d6ba40e3f1f2c639490
    user_id: 82e52e7a9e574d6ba40e3f1f2c639490
    device_trackers:
      - device_tracker.sm_g955f
      - device_tracker.galaxy_s8

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.11
    token: 5a52714147397869796a754e434c5674

fan:
  - platform: xiaomi_miio
    host: 192.168.1.27
    token: b8d8625068ac729c36e677462fecca53
#  - platform: template
#    fans:
#      anslut_fan:
#        friendly_name: "Anslut Fan"
#        value_template: "{{ states('switch.anslut_fan') }}"
#        oscillating_template: "{{ true if states('input_boolean.anslut_fan_oscillating') == 'on' else false }}"
#        set_oscillating:
#          service: script.turn_on
#          entity_id: script.anslut_fan_swing
#        turn_on:
#          service: script.anslut_fan_turn_on
#        turn_off:
#          service: script.anslut_fan_turn_off


input_text:
  broadcast:
    name: Broadcast
    initial: Some text

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include automations_manual.yaml
script: !include scripts.yaml
switch: !include switches.yaml
