---

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.3097048
  longitude: 18.0752532
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    automation:
      hidden: true

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: https://carlb-hassio.duckdns.org

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
# https://www.home-assistant.io/components/history
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - remote
    entities:
      - group.transmission
      - group.transmission_2
      - group.default_view
      - group.default_view_2
      - group.other_view
      - group.other_view_2
      - group.yr
      - group.yr_2
      - group.harmony_hub
      - group.harmony_hub_2
      - group.transmission
      - group.transmission_2
      - group.performance
      - group.performance_2
      - group.media_players
      - group.media_players_2
      - group.devices
      - group.devices_2
      - group.all_automations
      - group.all_automations_2
      - group.all_devices
      - group.all_devices_2
      - group.all_remotes
      - group.all_remotes_2
      - group.all_switches
      - group.all_switches_2
      - group.all_lights
      - group.all_lights_2
      - group.all_devices
      - group.all_devices_2
      - input_boolean.test
      - sensor.sl_skanstull

# View all events in a logbook
logbook:

# Configure data collection
# https://www.home-assistant.io/addons/mariadb
#recorder:
#  db_url: mysql://hass:hass@core-mariadb/homeassistant
#  purge_keep_days: 5

recorder:
  db_url: mysql://hassio:hassio@192.168.1.2/hassio

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

light:
  - platform: group
    name: Kitchen Table
    entities:
      - light.kitchen_table_left
      - light.kitchen_table_right

  - platform: group
    name: Kitchen Fan
    entities:
      - light.kitchen_fan_left
      - light.kitchen_fan_right

  - platform: group
    name: Living Area Lights
    entities:
      - light.bed
      - light.behind_tv
      - light.desktop
      - light.kitchen_fan

  - platform: template
    lights:
      desktop:
        friendly_name: Desktop
        entity_id:
          - switch.desktop
        value_template: '{{ is_state("switch.desktop", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.desktop
        turn_off:
          service: switch.turn_off
          entity_id: switch.desktop
      bathroom_ceiling:
        friendly_name: Bathroom Ceiling
        entity_id:
          - switch.bathroom_ceiling
        value_template: '{{ is_state("switch.bathroom_ceiling", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.bathroom_ceiling
        turn_off:
          service: switch.turn_off
          entity_id: switch.bathroom_ceiling

# Weather prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: load_1m
  - platform: transmission
    host: 192.168.1.2
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
      - 'active_torrents'
    username: cada
    password: !secret transmission_password
  - platform: tellstick
  - platform: template
    sensors:
      harmony_hub:
        friendly_name: "Harmony Hub"
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
  - platform: time_date
    display_options:
      - 'date_time'

binary_sensor:
  - platform: template
    sensors:
      harmony_hub_watch_tv:
        friendly_name: "Shield"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "SHIELD") }}'
      harmony_hub_home:
        friendly_name: "Home"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Home") }}'
      harmony_hub_away:
        friendly_name: "Away"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Away") }}'
      harmony_hub_clean:
        friendly_name: "Clean"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Clean") }}'

climate:
  - platform: generic_thermostat
    name: temperature_outside_skanstull
    heater: input_boolean.fake_heater
    target_sensor:  sensor.235_temperature
    initial_operation_mode: "off"
    target_temp: 21

# Text to speech
tts:
  - platform: google

# Cloud
# https://www.home-assistant.io/cloud/google_assistant/
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - scene
        - script
        - climate
      include_entities:
        - input_boolean.toaster
        - input_boolean.movie
      exclude_entities:
        - switch.toaster
        - switch.nexa_remote_g
        - light.kitchen_table_left
        - light.kitchen_table_right
        - light.kitchen_fan_left
        - light.kitchen_fan_right
        - switch.desktop
        - switch.bathroom_ceiling

    entity_config:
      light.desktop:
        room: Office
      light.bathroom_ceiling:
        room: Bathroom
      light.hallway_ceiling:
        room: Hallway
      light.kitchen_table:
        room: Kitchen

# Tellstick
tellstick:
  host: core-tellstick
  port: [50800, 50801]
  signal_repetitions: 10

zone:
  - name: home
    latitude: 59.3097048
    longitude: 18.0752532
    radius: 100
    icon: mdi:account-multiple
  - name: work
    latitude: 59.346727
    longitude: 18.0391455
    radius: 100
    icon: mdi:briefcase
  - name: 'Vida Pole'
    latitude: 59.336491
    longitude: 18.026207
    radius: 100
    icon: mdi:run-fast
  - name: 'Ann-Marie'
    latitude: 59.265861
    longitude: 18.089933
    radius: 100
    icon: mdi:account
  - name: 'Diskussionsgrupp'
    latitude: 59.328858
    longitude: 18.041308
    radius: 100
    icon: mdi:account-multiple

device_tracker:
  # https://www.home-assistant.io/components/device_tracker.asuswrt
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret router_password
    interval_seconds: 10
  - platform: google_maps
    username: carl.backstrom.dahl.location@gmail.com
    password: !secret location_gmail_password
  # https://www.home-assistant.io/components/device_tracker.icloud/
  - platform: icloud
    username: johanna.sjoestrand@gmail.com
    password: !secret johanna_icloud_password
    max_interval: 1
  - platform: bluetooth_tracker

media_player:
  - platform: kodi
    host: 192.168.1.7
    # https://github.com/home-assistant/home-assistant/issues/6546
    enable_websocket: false
    turn_off_action:
      - service: media_player.media_stop
        data:
          entity_id: media_player.kodi
  # https://home-assistant.io/components/media_player.spotify/
  - platform: spotify
    client_id: ea8908607667466486a0f8c404e7d944
    client_secret: !secret spotify_client_secret
    # https://community.home-assistant.io/t/spotify-ignoring-source/18588/24
    # Retrieve the alias adding by setting log level to info and grepping for "New "
    # tail -f /config/home-assistant.log | grep "New "
    aliases:
      41958a95210503efdf1a3271a6974e5083ed49d8: 'SRS-X77'
      3aacd1018a63677eee17183ac10f4f7685c056ef: 'Galaxy S8+'
  - platform: plex


influxdb:
  host: 192.168.1.2

logger:
  default: info
  logs:
    homeassistant.components.media_player.spotify: info

input_boolean:
  toaster:
    initial: false
  test:
    initial: false
  movie:
    initial: false
  camac:
    initial: true
  fake_heater:
    initial: false
  z9124:
    initial: false

timer:
  toaster:
    name: Toaster Timer
    duration: '00:02:00'
  clean:
    name: Clean Timer
    duration: '00:30:00'

# https://www.home-assistant.io/components/twilio
# twilio:
#   account_sid: 'AC9bd4546dbb927abc6694554cbe82ba50'
#   auth_token: !secret twilio_auth_token

notify:
  - name: 'pushover'
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
# https://www.home-assistant.io/components/notify.twilio_sms
# - name: 'twilio_sms'
#   platform: twilio_sms
#   from_number: '+46765193997'

remote:
  - platform: harmony
    name: Harmony Hub
    activity: Home

weather:
  - platform: openweathermap
    api_key: 334db6c50929238ed1dde1457d533f03

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
