---

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.3097048
  longitude: 18.0752532
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    automation:
      hidden: true

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Configure Lovelace UI using yaml in ui-lovelace.yaml
# https://www.home-assistant.io/lovelace/yaml-mode
lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: https://hassio.dahler.se
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.1
    - 127.0.0.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
# https://www.home-assistant.io/components/history
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - remote
    entities:
      - group.transmission
      - group.transmission_2
      - group.default_view
      - group.default_view_2
      - group.other_view
      - group.other_view_2
      - group.yr
      - group.yr_2
      - group.harmony_hub
      - group.harmony_hub_2
      - group.transmission
      - group.transmission_2
      - group.performance
      - group.performance_2
      - group.media_players
      - group.media_players_2
      - group.devices
      - group.devices_2
      - group.all_automations
      - group.all_automations_2
      - group.all_devices
      - group.all_devices_2
      - group.all_remotes
      - group.all_remotes_2
      - group.all_switches
      - group.all_switches_2
      - group.all_lights
      - group.all_lights_2
      - group.all_devices
      - group.all_devices_2
      - input_boolean.test
      - sensor.sl_skanstull

# https://www.home-assistant.io/components/logbook
logbook:

# https://www.home-assistant.io/addons/mariadb
recorder:
  db_url: mysql://hassio:hassio@192.168.1.2/hassio
  purge_keep_days: 2
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - zone
      - climate
    entities:
      - sensor.date_time
      - sensor.dafang
      - device_tracker.dafang
      - switch.dafang_h264_rtsp_server
      - switch.dafang_mjpeg_rtsp_server
      - sensor.dafang
      - switch.dafang_ir_filter
      - switch.dafang_ir_led
      - switch.dafang_night_mode_auto
      - switch.dafang_blue_led
      - switch.dafang_yellow_led
      - switch.dafang_motion_detection
      - switch.dafang_motion_tracking
      - camera.dafang_motion_snapshot
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      - sensor.custom_python_script_tracker

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

light:
  - platform: group
    name: Kitchen Table
    entities:
      - light.kitchen_table_left
      - light.kitchen_table_right

  - platform: group
    name: Kitchen Fan
    entities:
      - light.kitchen_fan_left
      - light.kitchen_fan_right

  - platform: group
    name: Living Room Ceiling
    entities:
      - light.living_room_ceiling_1
      - light.living_room_ceiling_2
      - light.living_room_ceiling_3

  - platform: group
    name: Living Area Lights
    entities:
      - light.bed
      - light.behind_tv
      - light.desktop
      - light.kitchen_fan

  - platform: template
    lights:
      bathroom_ceiling:
        friendly_name: Bathroom Ceiling
        entity_id:
          - switch.bathroom_ceiling
        value_template: '{{ is_state("switch.bathroom_ceiling", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.bathroom_ceiling
        turn_off:
          service: switch.turn_off
          entity_id: switch.bathroom_ceiling

sensor:
  # Weather prediction
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: load_1m
  - platform: tellstick
  # https://www.home-assistant.io/components/template
  - platform: template
    sensors:
      harmony_hub:
        friendly_name: "Harmony Hub"
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      air_purifier_humidity:
        value_template: "{{ states.fan.xiaomi_miio_device.attributes.humidity }}"
        friendly_name: Air Purifier Humidity
        unit_of_measurement: "%"
        device_class: humidity
      air_purifier_temperature:
        value_template: "{{ states.fan.xiaomi_miio_device.attributes.temperature }}"
        friendly_name: Air Purifier Temperature
        unit_of_measurement: "°C"
        device_class: temperature
      s10_batterylevel:
        value_template: "{{ states.device_tracker.google_maps_118136931442668540655.attributes.battery_level }}"
        friendly_name: Samsung S8 Battery Level (test)
        unit_of_measurement: "%"
        device_class: battery
  - platform: time_date
    display_options:
      - 'date_time'
  - platform: fitbit
    clock_format: 24H
    monitored_resources:
      - "body/weight"

  - platform: xiaomi_miio
    name: Xiaomi Air Quality Monitor
    host: 192.168.1.27
    token: b46710d6766df2f282339423f8d2c3e6

binary_sensor:
  - platform: template
    sensors:
      harmony_hub_watch_tv:
        friendly_name: "Watch TV"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Watch TV") }}'
      harmony_hub_home:
        friendly_name: "Home"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Home") }}'
      harmony_hub_away:
        friendly_name: "Away"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Away") }}'
      harmony_hub_clean:
        friendly_name: "Clean"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Clean") }}'
      harmony_hub_play_switch:
        friendly_name: "Play Switch"
        value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Play Switch") }}'

climate:
  - platform: generic_thermostat
    name: temperature_outside_skanstull
    heater: input_boolean.fake_heater
    target_sensor:  sensor.235_temperature
    initial_operation_mode: "off"
    target_temp: 21

# Text to speech
tts:
  - platform: google_translate

# Cloud
# https://www.home-assistant.io/cloud/google_assistant/
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - scene
        - script
        - climate
      exclude_entities:
        - switch.nexa_remote_g
        - light.kitchen_table_left
        - light.kitchen_table_right
        - light.kitchen_fan_left
        - light.kitchen_fan_right
        - switch.desktop
        - switch.bathroom_ceiling

    entity_config:
      light.desktop:
        room: Office
      light.bathroom_ceiling:
        room: Bathroom
      light.hallway_ceiling:
        room: Hallway
      light.kitchen_table:
        room: Kitchen
      switch.coffeemaker:
        room: Kitchen
      switch.toaster:
        room: Kitchen
      script.clean_kitchen:
        room: Kitchen

# Tellstick
tellstick:
  host: core-tellstick
  port: [50800, 50801]
  signal_repetitions: 3

zone:
  - name: home
    latitude: 59.3097048
    longitude: 18.0752532
    radius: 100
    icon: mdi:account-multiple
  - name: work
    latitude: 59.346727
    longitude: 18.0391455
    radius: 100
    icon: mdi:briefcase
  - name: 'Vida Pole'
    latitude: 59.336491
    longitude: 18.026207
    radius: 100
    icon: mdi:run-fast
  - name: 'Ann-Marie'
    latitude: 59.265861
    longitude: 18.089933
    radius: 100
    icon: mdi:account
  - name: 'Diskussionsgrupp'
    latitude: 59.328858
    longitude: 18.041308
    radius: 100
    icon: mdi:account-multiple

# https://www.home-assistant.io/components/asuswrt/
asuswrt:
  host: 192.168.1.1
  username: admin
  password: !secret router_password

device_tracker:
  - platform: google_maps
    username: carl.backstrom.dahl.location@gmail.com
    password: !secret location_gmail_password
  # https://www.home-assistant.io/components/device_tracker.icloud/
  - platform: icloud
    username: johanna.sjoestrand@gmail.com
    password: !secret johanna_icloud_password
    max_interval: 1
  # https://www.home-assistant.io/components/device_tracker.asuswrt/
  - platform: asuswrt

media_player:
  - platform: kodi
    host: 192.168.1.7
    # https://github.com/home-assistant/home-assistant/issues/6546
    enable_websocket: false
    turn_off_action:
      - service: media_player.media_stop
        data:
          entity_id: media_player.kodi
  # https://home-assistant.io/components/media_player.spotify/
  - platform: spotify
    client_id: ea8908607667466486a0f8c404e7d944
    client_secret: !secret spotify_client_secret
    # https://community.home-assistant.io/t/spotify-ignoring-source/18588/24
    # Retrieve the alias adding by setting log level to info and grepping for "New "
    # tail -f /config/home-assistant.log | grep "New "
    aliases:
      41958a95210503efdf1a3271a6974e5083ed49d8: 'SRS-X77'
      3aacd1018a63677eee17183ac10f4f7685c056ef: 'Galaxy S8+'
  # https://www.home-assistant.io/components/media_player.plex
  - platform: plex
    entity_namespace: plex
    remove_unavailable_clients: false

influxdb:
  host: 192.168.1.2

logger:
  default: info
  logs:
    homeassistant.components.media_player.spotify: info

input_boolean:
  test:
    initial: false
  movie:
    initial: false
  camac:
    initial: true
  fake_heater:
    initial: false

input_number:
  xiaomi_fan_favorite_level:
    name: Xiaomi Fan Favourite Level
    min: 0
    max: 14
    step: 1

timer:
  clean:
    name: Clean Timer
    duration: '00:30:00'
  toaster:
    name: Toaster Timer
    duration: '00:02:00'
  coffeemaker:
    name: Coffeemaker Timer
    duration: '00:60:00'

notify:
  - name: 'pushover'
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

remote:
  - platform: harmony
    name: Harmony Hub
    activity: Home

camera:
  - platform: ffmpeg
    name: DaFang
    input: -rtsp_transport tcp -i rtsp://192.168.1.208:8554/unicast

# https://github.com/custom-components/custom_updater/wiki/Installation
custom_updater:
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    # https://community.home-assistant.io/t/lovelace-mini-media-player/68459
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json

mqtt:
  broker: 192.168.1.4
  discovery: true
  discovery_prefix: homeassistant
  username: homeassistant
  password: !secret mqtt_password

panel_iframe:
  dafang:
    icon: mdi:camera
    title: Dafang Camera
    url: 'https://192.168.1.208'

system_health:

person:
  - name: Carl
    id: ddbc7a2301d74d609308958f9f07d0b7
    device_trackers:
      - device_tracker.google_maps_118136931442668540655
#      - device_tracker.carl_s8_router
  - name: Johanna
    id: 82e52e7a9e574d6ba40e3f1f2c639490
    device_trackers:
      - device_tracker.iphone
#      - device_tracker.johanna_iphone_router

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.12
    token: 50366952685a5945696c416f74783341

fan:
  - platform: xiaomi_miio
    host: 192.168.1.27
    token: b46710d6766df2f282339423f8d2c3e6




group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
