- platform: tellstick
- platform: template
  switches:
    harmony_hub_watch_tv:
      value_template: "{{ is_state('binary_sensor.harmony_hub_watch_tv', 'on') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch TV'
    harmony_hub_clean:
      value_template: "{{ is_state('binary_sensor.harmony_hub_clean', 'on') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Clean
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: Clean
    harmony_hub_home:
      value_template: "{{ is_state('binary_sensor.harmony_hub_home', 'on') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Home
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: Home
    harmony_hub_play_switch:
      value_template: "{{ is_state('binary_sensor.harmony_hub_play_switch', 'on') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Play Switch'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: 'Play Switch'
