- platform: tellstick
- platform: template
  switches:
    xiaomi_smart_fan_oscillate:
      value_template: '{{ states.fan.xiaomi_smart_fan.attributes.oscillate }}'
      turn_on:
        service: fan.oscillate
        data:
          entity_id: fan.xiaomi_smart_fan
          oscillating: true
      turn_off:
        service: fan.oscillate
        data:
          entity_id: fan.xiaomi_smart_fan
          oscillating: false
