title: Götgatan 94
custom_header:
  compact_mode: true
views:
  - icon: mdi:home-assistant
    # View tab title.
    title: Main
    # Optional unique id for direct access /lovelace/${id}
    id: main
    cards:
      - type: weather-forecast
        entity: weather.smhi_home
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.235_temperature
            name: Temp - Outside
            height: 60
            width: 30
            line_color: "#3498db"
          - type: sensor
            entity: sensor.air_purifier_temperature
            name: Temp - Inside
            height: 60
            width: 30
            line_color: "#3498db"

      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.aqara_humidity_1
            name: Humidity - Inside
            height: 60
            width: 30
            line_color: "#3498db"
          - type: sensor
            entity: sensor.aqara_pressure_1
            name: Pressure - Inside
            height: 60
            width: 30
            line_color: "#3498db"
          - type: sensor
            entity: sensor.aqara_temperature_1
            name: Temperature - Inside
            height: 60
            width: 30
            line_color: "#3498db"


      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.air_purifier_humidity
            name: Humidity - Inside
            height: 60
            width: 30
            line_color: "#3498db"
          - type: sensor
            entity: sensor.air_purifier_air_quality
            name: Air Quality - Inside
            height: 60
            width: 30
          - type: sensor
            entity: sensor.sm_g975f_battery_level
            name: S10 Battery
            height: 60
            width: 30
          - type: sensor
            entity: sensor.sm_g955f_battery_level
            name: S8 Battery
            height: 60
            width: 30
      - type: glance
        entities:
          - sensor.weight
          - sensor.ionic_battery
          - sensor.sleep_time_in_bed
          - sensor.tracker_steps

      - type: entity-filter
        entities:
          - person.carl
          - person.johanna
        state_filter:
          - 'home'
        card:
          type: glance
          show_state: false
          show_name: false
          title: '@home'
      - type: glance
        entities:
          - timer.toaster
          - timer.coffeemaker
          - timer.clean
      - type: glance
        title: Scenes
        show_header_toggle: false
        show_state: false
        entities:
          - entity:  script.media_dark
            tap_action:
              action: toggle
          - entity: script.media_backlight
            tap_action:
              action: toggle
          - entity: script.computer
            tap_action:
              action: toggle
          - entity: script.daytime
            tap_action:
              action: toggle
          - entity: script.cozy
            tap_action:
              action: toggle
          - entity: script.sleep_in_ten_min
            tap_action:
              action: toggle
          - entity: script.sleep_now
            tap_action:
              action: toggle
          - entity: script.sleep_in_an_hour
            tap_action:
              action: toggle
          - entity: script.work
            tap_action:
              action: toggle
          - entity: script.dinner
            tap_action:
              action: toggle
          - entity: script.early_morning
            tap_action:
              action: toggle
          - entity: script.clean_kitchen
            tap_action:
              action: toggle
          - entity: script.clean_hallway
            tap_action:
              action: toggle
          - entity: script.clean_living_room
            tap_action:
              action: toggle
          - entity: script.xiaomi_vacuum_cleaner_go_to_emptying_spot
            tap_action:
              action: toggle
          - entity: script.rotel_phono_mode
            tap_action:
              action: toggle


      - type: glance
        show_header_toggle: false
        show_state: false
        title: Motion Sensors
        entities:
          - entity: binary_sensor.hallway_motion_sensor
            name: Hallway
#          - entity: binary_sensor.bathroom_motion_sensor
#            name: Bathroom

      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: light.desktop
            name: Desktop
#          - type: entity-button
#            entity: light.bathroom_ceiling
          - type: custom:slider-entity-row
            entity: light.hallway_ceiling
            name: Hallway
          - type: custom:slider-entity-row
            entity: light.kitchen_table
            name: Kitchen Table
          - type: custom:slider-entity-row
            entity: light.kitchen_fan
            name: Kitchen Fan
          - type: custom:slider-entity-row
            entity: light.bed
            name: Bed
          - type: custom:slider-entity-row
            entity: light.behind_tv
            name: TV
          - type: custom:slider-entity-row
            entity: light.frank
            name: Frank
          - type: custom:slider-entity-row
            entity: light.living_room_ceiling
            name: LR Ceiling
          - type: custom:slider-entity-row
            entity: light.living_area_lights
            name: Living Area

      - type: glance
        title: Switches
        show_state: false
        entities:
          - entity: switch.toaster
            name: Toaster
            tap_action:
              action: toggle
          - entity: switch.coffeemaker
            name: Coffeemaker
            icon: mdi:coffee
            tap_action:
              action: toggle
          - entity: switch.screen
            name: Screen
            icon: mdi:monitor
            tap_action:
              action: toggle

      - type: entities
        title: Devices
        show_header_toggle: false
        entities:
          - vacuum.xiaomi_vacuum_cleaner
          - fan.xiaomi_miio_device
          - input_number.xiaomi_fan_favorite_level
          - fan.anslut_fan

      - type: entity-filter
        entities:
          - device_tracker.android4749e9acd4fc4284 # Natalie Milz
          - device_tracker.patriksmbp # Patrik
        state_filter:
          - 'home'
        show_empty: false
        card:
          type: glance
          title: Friends
      # https://community.home-assistant.io/t/lovelace-mini-media-player/68459
      - type: entities
        title: Media Players
        entities:
          - entity: media_player.spotify_carl_backstrom
            type: custom:mini-media-player
          - entity: media_player.shield
            type: custom:mini-media-player
          - entity: media_player.lg_tv
            type: custom:mini-media-player
          - entity: media_player.home_group
            type: custom:mini-media-player
            hide_controls: true
            show_tts: google
          - entity: media_player.kitchen_speaker
            type: custom:mini-media-player
            hide_controls: true
            show_tts: google
          - entity: media_player.office_speaker
            type: custom:mini-media-player
            hide_controls: true
            show_tts: google

      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_text.broadcast
            name: Announce It...
          - entity: script.broadcast
        title: Make an Announcement
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner


  - title: Tracker
    id: tracker
    icon: mdi:crosshairs-gps
    # Title of the view. Will be used as the tooltip for tab icon
    cards:
      - type: map
        aspect_ratio: 50%
        entities:
        - person.carl
        - person.johanna
        - zone.home
      - type: history-graph
        title: History
        entities:
          - group.tracker_home
          - person.carl
          - person.johanna
          - switch.screen

  - title: Remote
    id: remote
    icon: mdi:remote
    cards:
      - type: glance
        title: Remote
        show_state: false
        columns: 3
        entities:
          # Row 1
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56823523
                "command": VolumeUp
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:chevron-up-box-outline
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": DirectionUp
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:play-pause
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": Play
          # Row 2
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:chevron-left-box-outline
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": DirectionLeft
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:checkbox-blank-circle-outline
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": Select
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:chevron-right-box-outline
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": DirectionRight

          # Row 3
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56823523
                "command": VolumeDown
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:chevron-down-box-outline
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": DirectionDown
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:keyboard-backspace
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": Back

          # Shield Intents https://gist.github.com/mcfrojd/9e6875e1db5c089b1e3ddeb7dba0f304
          # Row 3
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:home
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": Home
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:sleep
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": sleep
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:sleep
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                "entity_id": remote.harmony_hub
                "device": 56825777
                "command": sleep
          # Row 4
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:kodi
            tap_action:
              action: call-service
              service: androidtv.adb_command
              service_data:
                entity_id: media_player.shield_3
                command: "am start -a android.intent.action.VIEW -d -n org.xbmc.kodi/.Splash"
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:plex
            tap_action:
              action: call-service
              service: androidtv.adb_command
              service_data:
                entity_id: media_player.shield_3
                command: "am start -a android.intent.action.MAIN -c android.intent.category.LEANBACK_LAUNCHER -n com.plexapp.android/com.plexapp.plex.activities.SplashActivity"
          - entity: binary_sensor.dummy
            name: ''
            icon: mdi:youtube
            tap_action:
              action: call-service
              service: androidtv.adb_command
              service_data:
                entity_id: media_player.shield_3
                command: "am start -a android.intent.action.VIEW -d -n com.google.android.youtube.tv/com.google.android.apps.youtube.tv.activity.ShellActivity"
          # Row 5
          - entity: binary_sensor.dummy
            icon: mdi:play
            name: 'SVT'
            image: http://www.svtplay.se/favicon.ico
            tap_action:
              action: call-service
              service: androidtv.adb_command
              service_data:
                entity_id: media_player.shield_3
                command: "am start -a android.intent.action.VIEW -d -n se.svt.android.svtplay/se.svt.svtplay.tv.ui.StartupActivity"

