title: Götgatan 94
resources:
  - url: /local/mini-media-player-bundle.js?v=1.1.3
    type: module
  - url: /local/slider-entity-row.js?v=0.1
    type: js
  - url: /local/light-entity-row.js?v=0.2.4
    type: js
  - url: /local/circle-sensor-card.js?v=0
    type: module
  - url: /local/custom-lovelace/swipe-card/swipe-card.js
    type: module

views:
  - icon: mdi:home-assistant
    # View tab title.
    title: Main
    # Optional unique id for direct access /lovelace/${id}
    id: main
    theme: dark-mode
    cards:
      - type: custom:swipe-card
        card_width: '250px'
        start_card: 1
        parameters:
          effect: 'coverflow'
          grabCursor: true
          centeredSlides: true
          slidesPerView: 'auto'
          coverflowEffect:
            rotate: 50
            stretch: 0
            depth: 100
            modifier: 1
            slideShadows: true
          pagination:
            type: 'bullets'
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.235_temperature
                name: Temp - Outside
                height: 60
                width: 30
                line_color: "#3498db"
              - type: sensor
                entity: sensor.air_purifier_temperature
                name: Temp - Inside
                height: 60
                width: 30
                line_color: "#3498db"
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.air_purifier_humidity
                name: Humidity - Inside
                height: 60
                width: 30
                line_color: "#3498db"
              - type: sensor
                entity: sensor.xiaomi_air_quality_monitor
                name: Air Quality - Inside
                height: 60
                width: 30
              - type: sensor
                entity: sensor.s10_batterylevel
                name: Samsung S10 Battery Level
                height: 60
                width: 30
          - type: entity-filter
            entities:
              - person.carl
              - person.johanna
            state_filter:
              - 'home'
            card:
              type: glance
              show_state: false
              show_name: false
              title: '@home'
          - type: glance
            entities:
              - timer.toaster
              - timer.coffeemaker
              - timer.clean
      - type: custom:swipe-card
        cards:
          - type: glance
            title: Scenes
            show_header_toggle: false
            show_state: false
            entities:
              - entity:  script.media_dark
                tap_action:
                  action: toggle
              - entity: script.media_backlight
                tap_action:
                  action: toggle
              - entity: script.computer
                tap_action:
                  action: toggle
              - entity: script.daytime
                tap_action:
                  action: toggle
              - entity: script.cozy
                tap_action:
                  action: toggle
              - entity: script.sleep_in_ten_min
                tap_action:
                  action: toggle
              - entity: script.sleep_now
                tap_action:
                  action: toggle
              - entity: script.sleep_in_an_hour
                tap_action:
                  action: toggle
              - entity: script.work
                tap_action:
                  action: toggle
              - entity: script.dinner
                tap_action:
                  action: toggle
              - entity: script.early_morning
                tap_action:
                  action: toggle
              - entity: script.clean_kitchen
                tap_action:
                  action: toggle

          # https://www.home-assistant.io/lovelace/glance/
          - type: glance
            title: Harmony Hub
            show_header_toggle: false
            show_state: false
            entities:
              - entity: switch.harmony_hub_home
                icon: mdi:home
              - entity: binary_sensor.harmony_hub_away
                icon: mdi:home-minus
              - entity: switch.harmony_hub_watch_tv
                tap_action:
                  action: toggle
              - entity: switch.harmony_hub_clean
                tap_action:
                  action: toggle
              - entity: switch.harmony_hub_play_switch
                tap_action:
                  action: toggle

      - type: picture-glance
        title: Living room
        entities:
          - binary_sensor.dafang_motion_sensor
        camera_image: camera.dafang

      - type: glance
        show_header_toggle: false
        show_state: false
        title: Motion Sensors
        entities:
          - entity: binary_sensor.hallway_motion_sensor
            name: Hallway
          - entity: binary_sensor.bathroom_motion_sensor
            name: Bathroom

      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: light.desktop
            name: Desktop
          - type: entity-button
            entity: light.bathroom_ceiling
          - type: custom:slider-entity-row
            entity: light.hallway_ceiling
            name: Hallway
          - type: custom:slider-entity-row
            entity: light.kitchen_table
            name: Kitchen Table
          - type: custom:slider-entity-row
            entity: light.kitchen_fan
            name: Kitchen Fan
          - type: custom:slider-entity-row
            entity: light.bed
            name: Bed
          - type: custom:slider-entity-row
            entity: light.behind_tv
            name: TV
          - type: custom:slider-entity-row
            entity: light.living_room_ceiling
            name: Living Room Ceiling
          - type: custom:slider-entity-row
            entity: light.living_area_lights
            name: Living Area

      - type: glance
        title: Switches
        show_state: false
        entities:
          - entity: switch.toaster
            name: Toaster
            tap_action:
              action: toggle
          - entity: switch.coffeemaker
            name: Coffeemaker
            icon: mdi:coffee
            tap_action:
              action: toggle
          - entity: switch.screen
            name: Screen
            icon: mdi:monitor
            tap_action:
              action: toggle

      - type: entities
        title: Devices
        show_header_toggle: false
        entities:
          - vacuum.xiaomi_vacuum_cleaner
          - fan.xiaomi_miio_device
          - input_number.xiaomi_fan_favorite_level
          - fan.anslut_fan

      - type: entity-filter
        entities:
          - device_tracker.android4749e9acd4fc4284 # Natalie Milz
          - device_tracker.patriksmbp # Patrik
        state_filter:
          - 'home'
        show_empty: false
        card:
          type: glance
          title: Friends
      # https://community.home-assistant.io/t/lovelace-mini-media-player/68459
      - type: entities
        title: Media Players
        entities:
          - entity: media_player.spotify
            type: custom:mini-media-player
            group: true
          - entity: media_player.home
            type: custom:mini-media-player
            hide_controls: true
            show_tts: google
            group: true
          - entity: media_player.shield_android_tv_2
            type: custom:mini-media-player
            hide_controls: true
            group: true
          - entity: media_player.shield_3
            type: custom:mini-media-player


  - title: Tracker
    id: tracker
    # Title of the view. Will be used as the tooltip for tab icon
    cards:
      - type: map
        aspect_ratio: 50%
        entities:
        - person.carl
        - person.johanna
        - zone.home
      - type: history-graph
        title: History
        entities:
          - group.tracker_home
          - person.carl
          - person.johanna
          - switch.screen

  - title: Other
    id: other
    # Title of the view. Will be used as the tooltip for tab icon
    cards:
      - type: entities
        title: Performance
        entities:
          - sensor.load_1m
          - sensor.memory_free
          - sensor.memory_use
          - sensor.disk_use_percent
          - sensor.disk_use_percent_home
          - sensor.processor_use
          - sensor.processor_use

      - type: entities
        title: Devices+
        entities:
          - device_tracker.10c6fc8e7fa3 # Garmin Edge 1000
          - device_tracker.6c5697d9c323 # Johanna's Kindle
          - device_tracker.b827eb1c5c4e # RPI3
          - device_tracker.burken
          - device_tracker.camac
          - device_tracker.camac_2
          - device_tracker.hassio
          - device_tracker.ipad # Johanna's iPad
      - type: entities
        title: Dafang
        show_header_toggle: false
        entities:
          - camera.dafang
          - switch.dafang_h264_rtsp_server
          - switch.dafang_mjpeg_rtsp_server
          - device_tracker.dafang
          - sensor.dafang_light_sensor
          - switch.dafang_ir_filter
          - switch.dafang_ir_led
          - switch.dafang_night_mode
          - switch.dafang_night_mode_auto
          - switch.dafang_blue_led
          - switch.dafang_yellow_led
          - switch.dafang_motion_detection
          - switch.dafang_motion_tracking
          - camera.dafang_motion_snapshot
          - binary_sensor.dafang_motion_sensor
      - type: entities
        title: Lights
        entities:
          - type: "custom:light-entity-row"
            entity: light.kitchen_table
      - type: entities
        title: Other
        show_header_toggle: false
        entities:
          - sensor.daylight
          - binary_sensor.hallway_motion_sensor
          - binary_sensor.bathroom_motion_sensor
          - sensor.date_time
