title: My Awesome Home
# Include external resources
#resources:
#  - url: /local/my-custom-card.js
#    type: js
#  - url: /local/my-webfont.css
#    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views:
  - icon: mdi:home-assistant
    # View tab title.
    title: Main
    # Optional unique id for direct access /lovelace/${id}
    id: main
    # Optional background (overwrites the global background).
    # background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - group.tracker_carl
          - group.tracker_johanna
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home
      - type: entity-filter
        entities:
          - device_tracker.android4749e9acd4fc4284 # Natalie Milz
        state_filter:
          - 'home'
        show_empty: false
        card:
          type: glance
          title: Friends
      - type: glance
        title: Lights
        show_header_toggle: true
        show_state: false
        entities:
          - entity: light.desktop
            tap_action: toggle
          - entity: light.bathroom_ceiling
            tap_action: toggle
          - entity: light.hallway_ceiling
            tap_action: toggle
          - entity: light.kitchen_table
            tap_action: toggle
          - entity: light.kitchen_fan
            tap_action: toggle
          - entity: light.bed
            tap_action: toggle
          - entity: light.behind_tv
            tap_action: toggle
          - entity: light.living_area_lights
      - type: glance
        title: Harmony Hub
        show_header_toggle: false
        entities:
          - entity: switch.harmony_hub_home
            icon: mdi:home
          - entity: binary_sensor.harmony_hub_away
            icon: mdi:home-minus
          - entity: switch.harmony_hub_shield
            tap_action: toggle
          - entity: switch.harmony_hub_clean
            tap_action: toggle
      - type: glance
        title: Scenes
        show_header_toggle: false
        show_state: false
        entities:
          - entity:  script.tv_dark
            tap_action: toggle
          - entity: script.tv_backlight
            tap_action: toggle
          - entity: script.computer
            tap_action: toggle
          - entity: script.default
            tap_action: toggle
          - entity: script.cozy
            tap_action: toggle
          - entity: script.sleep
            tap_action: toggle
          - entity: script.dinner
            tap_action: toggle
          - entity: script.industrial

      - type: entities
        title: Other
        show_header_toggle: false
        entities:
          - input_boolean.toaster
          - timer.toaster
          - timer.clean
          - entity: switch.screen
            name: Screen Switch
            icon: mdi:monitor
          - sensor.daylight
          - binary_sensor.hallway_motion_sensor
          - binary_sensor.bathroom_motion_sensor
#          - sensor.sl_skanstull
          - entity: sensor.235_temperature
            name: Temperature - Outside - Skanstull
            icon: mdi:thermometer
          - sensor.date__time
      - type: media-control
        entity: media_player.spotify
      - type: media-control
        entity: media_player.srsx77
      - type: map
        aspect_ratio: 50%
        entities:
          - device_tracker.google_maps_118136931442668540655
          - device_tracker.iphone
          - zone.home

      - type: glance
        title: Z9124
        show_header_toggle: false
        show_state: false
        entities:
          - entity: script.z9124_toggle
            name: Toogle
            icon: mdi:power
            tap_action: toggle
          - entity: script.z9124_auto
            name: Auto
            icon: mdi:robot
            tap_action: toggle
          - entity: script.z9124_quiet
            name: Quiet
            icon: mdi:volume-mute
            tap_action: toggle
          - entity: script.z9124_turbo
            name: Turbo
            icon: mdi:fast-forward
            tap_action: toggle
          - entity: script.z9124_medium
            name: Medium
            tap_action: toggle
    # Specify a tab icon if you want the view tab to be an icon.
  - title: Other
    id: other
    # Title of the view. Will be used as the tooltip for tab icon
    cards:
      - type: entities
        title: Performance
        entities:
          - sensor.load_1m
          - sensor.memory_free
          - sensor.memory_use
          - sensor.disk_use_percent_
          - sensor.disk_use_percent_home
          - sensor.processor_use
          - sensor.processor_use
      - type: entities
        title: Transmission
        entities:
          - sensor.transmission_active_torrents
          - sensor.transmission_down_speed
          - sensor.transmission_status
          - sensor.transmission_up_speed

      - type: entities
        title: Devices+
        entities:
          - device_tracker.10c6fc8e7fa3 # Garmin Edge 1000
          - device_tracker.6c5697d9c323 # Johanna's Kindle
          - device_tracker.b827eb1c5c4e # RPI3
          - device_tracker.burken
          - device_tracker.camac
          - device_tracker.camac_2
          - device_tracker.hassio
          - device_tracker.ipad # Johanna's iPad
          - device_tracker.shield
      - type: weather-forecast
        entity: weather.openweathermap
